### ISSUE TITLE
README.md can not work

### ISSUE THREAD

**Issue by ymlisoft** [jboss-developer/jboss-wfk-quickstarts#218]
I followed the v2.7.0 README.md, but build failed. Are you sure the doc was tested via a empty project?

jboss-kitchensink-rf

Missing artifact org.richfaces:richfaces:jar:4.5.1.Final-redhat-1

**Comment by joshuawilson** [comment]
Can you please try installing the BOMs from https://github.com/jboss-developer/jboss-wfk-boms

You appear to be referencing the in development version of code and that means that not all the supporting jars have been pushed to the public maven repos yet.

**Comment by ymlisoft** [comment]
Thanks for your help!
I changed the jar version to 4.5.0.Final, and it works well.
Btw, when can we get the 2.7 final version?
